### ISSUE TITLE
How to force hotreload when using a 'new' class?

### ISSUE THREAD

**Issue by realtebo** [lucleray/next-purgecss#11]
I try to explain the situation.

I am importing bootstrap

    @import "~bootstrap/scss/bootstrap";

Then in my Index pge 
```

const Index = () => (
  <div className="bg-success">
    <p className='text-warning'>Hello Next.js</p>
  </div>
)

export default Index

```

As you can see, I asked to have a red background (using bg-success) className. And this works.

Then I remove `bg-success`.

And hot reload works

Then I add 'bg-danger' 

Next see the difference, the css is recreated, but the new .css is not used; i must press F5 to reload. manually.

Is there a way to keep working the hot reload?

**Comment by lucleray** [comment]
That's a good point !

A workaround to avoid this is to disable the plugin when using `next dev`, like this :

```js
// next.config.js
const withPurgeCss = require('next-purgecss')
const {PHASE_DEVELOPMENT_SERVER} = require('next/constants')

module.exports = phase =>
  phase !== PHASE_DEVELOPMENT_SERVER ?
    withCss(withPurgeCss()) :
    withCss()
```

I'll try to see if this can be solved without this workaround 🙂

**Comment by realtebo** [comment]
Thanks for your kindle suggestion, but I do not want to disable nothing in development.

Is this a bug? A wanted featured? ... Or what ?

**Comment by realtebo** [comment]
Also, Adding 2 duplicated defs, the plugin do not remove  one of them neither after

    npm run build
    npm start

**Comment by lucleray** [comment]
I would say it's a bug, but I'm not sure it's something this package can solve. I'll try to dig further.

Otherwise it's either nextjs or purgecss-webpack-plugin.

For the duplicate defs, then it's something related to purgecss itself, you should open an issue there 🙂

**Comment by millette** [comment]
I use a workaround similar to @lucleray:

```js
const withPurgeCss =
  process.env.NODE_ENV === "production" ? require("next-purgecss") : (x) => x
```
which simply passes through its argument in dev.

**Comment by AlexVipond** [comment]
I added pull request #20 to make it easier for users to enable/disable the plugin based on environment

**Comment by millette** [comment]
Can we consider this issue closed now that <https://github.com/lucleray/next-purgecss#purgecssenabled> is avalable?

**Comment by AlexVipond** [comment]
I think `purgeCssEnabled` doesn't directly solve @realtebo 's problem but offers a best practice that should be followed instead: during development, just don't purge your CSS. 

If there are still issues with hot reloading after disabling purgecss, the problem is coming from somewhere else in the webpack config and not with `next-purgecss` or its dependencies.

I vote safe to close 🚀

**Comment by lucleray** [comment]
I'll close 🙂
