### ISSUE TITLE
why it removed used style class in component from node_module?

### ISSUE THREAD

**Issue by WoraponU** [lucleray/next-purgecss#13]
I use react-slick from node_module but when i use next-purgecss that it remove used style class in react-slick?

main.scss
![image](https://user-images.githubusercontent.com/13904659/54586216-f0d66e00-4a4e-11e9-8a4c-429c09d676db.png)

next.config.js
![image](https://user-images.githubusercontent.com/13904659/54586337-4f035100-4a4f-11e9-9e22-e65134a992a7.png)

and i import '../sass/main.scss' in  _app.js

thankyou

**Comment by lucleray** [comment]
I can't help you with just this information but I can help investigate if you share a reproduction repo :)
