### ISSUE TITLE
ReferenceError: options is not defined

### ISSUE THREAD

**Issue by msheakoski** [lucleray/next-purgecss#21]
This error was introduced in commit 38d876e because the options variable is no longer declared in the function scope.

https://github.com/lucleray/next-purgecss/commit/38d876e8fabc2ed93adb7206f8a959fb882d3418#r34078744

**Comment by lucleray** [comment]
Thank you for reporting the issue!

Fixing now.

**Comment by lucleray** [comment]
I published the fixed in `3.1.1`. Thank you 🙏
