### ISSUE TITLE
A small mistake in documentation.

### ISSUE THREAD

**Issue by PanLydka** [lucleray/next-purgecss#24]
Hi, propably I found a small mistake.
[purgeCssEnabled](https://github.com/lucleray/next-purgecss#purgecssenabled)

The argument in function is called differently.
`module.exports = withCss(
  withPurgeCss({
    purgeCssEnabled: ({ dev, isServer }) => (!isDev && !isServer) // Only enable PurgeCSS for client-side production builds
  })
)`

probably should be
``module.exports = withCss(
  withPurgeCss({
    purgeCssEnabled: ({ isDev, isServer }) => (!isDev && !isServer) // Only enable PurgeCSS for client-side production builds
  })
)``

**Comment by lucleray** [comment]
I updated, thank you 🙏
