### ISSUE TITLE
how to use with composePlugins

### ISSUE THREAD

**Issue by bhkim526** [lucleray/next-purgecss#34]
I got below in next.config.js and trying to use next-purgecss. I am not sure how to though. could you please shed some light on it? Thank you so much.

const nextConfig = {webpack: (config, options) => {...}}
module.exports = composePlugins([
   [typescript],
   [css, {...}],
   [sass, {...}]
], nextConfig)

**Comment by lucleray** [comment]
I've reopened issue #9 so we can continue the discussion there 🙂
